### ISSUE TITLE
Topology::cpuset causes segfault

### ISSUE THREAD

**Issue by uglyoldbob** [HadrienG2/hwlocality#27]
I have a function that looks like this:
```
pub fn example(mut tp: hwlocality::topology::Topology) {
    let cpuset = tp.cpuset();

    for index in cpuset.iter_set().map(usize::from).collect::<Vec<_>>() {
        println!("cpu {}", index);
    }
}
```
I call it like this:
```
example(tp.clone());
```

Here is a backtrace:
```
#0  0x00005555556bc6e5 in hwloc_bitmap_next (set=0x0, prev_cpu=0) at /home/thomas/hwlocality/hwloc/hwloc/bitmap.c:1402
#1  0x00005555556edbe3 in hwlocality::bitmaps::{impl#0}::next_set::{closure#0} (bitmap=0x0, prev=0) at src/bitmaps/mod.rs:868
#2  0x00005555556edaed in hwlocality::bitmaps::Bitmap::next<hwlocality::bitmaps::{impl#0}::next_set::{closure_env#0}> (self=0x7fffffffce18, index=..., next_fn=...)
    at src/bitmaps/mod.rs:854
#3  0x00005555556a0d46 in hwlocality::bitmaps::Bitmap::next_set (self=0x7fffffffce18, index=...) at src/bitmaps/mod.rs:867
#4  0x00005555556678d2 in hwlocality::bitmaps::{impl#32}::next<&hwlocality::bitmaps::Bitmap> (self=0x7fffffffcd90)
    at /home/thomas/hwlocality/src/bitmaps/mod.rs:1189
#5  0x0000555555615fe3 in core::iter::adapters::map::{impl#2}::next<usize, hwlocality::bitmaps::BitmapIterator<&hwlocality::bitmaps::Bitmap>, fn(hwlocality::bitmaps::indices::BitmapIndex) -> usize> (self=0x7fffffffcd90) at /rustc/8c74a5d27c644a0f7a22bb2fa8dd3ff8257bc220/library/core/src/iter/adapters/map.rs:103
#6  0x0000555555686c19 in alloc::vec::Vec<usize, alloc::alloc::Global>::extend_desugared<usize, alloc::alloc::Global, core::iter::adapters::map::Map<hwlocality::bitmaps::BitmapIterator<&hwlocality::bitmaps::Bitmap>, fn(hwlocality::bitmaps::indices::BitmapIndex) -> usize>> (self=0x7fffffffcd30, iterator=...)
    at /rustc/8c74a5d27c644a0f7a22bb2fa8dd3ff8257bc220/library/alloc/src/vec/mod.rs:2795
#7  0x00005555556895da in alloc::vec::spec_extend::{impl#0}::spec_extend<usize, core::iter::adapters::map::Map<hwlocality::bitmaps::BitmapIterator<&hwlocality::bitmaps::Bitmap>, fn(hwlocality::bitmaps::indices::BitmapIndex) -> usize>, alloc::alloc::Global> (self=0x7fffffffcd30, 
    iter=<error reading variable: Cannot access memory at address 0x0>) at /rustc/8c74a5d27c644a0f7a22bb2fa8dd3ff8257bc220/library/alloc/src/vec/spec_extend.rs:17
#8  0x0000555555685ddd in alloc::vec::spec_from_iter_nested::{impl#0}::from_iter<usize, core::iter::adapters::map::Map<hwlocality::bitmaps::BitmapIterator<&hwlocality::bitmaps::Bitmap>, fn(hwlocality::bitmaps::indices::BitmapIndex) -> usize>> (iterator=...)
    at /rustc/8c74a5d27c644a0f7a22bb2fa8dd3ff8257bc220/library/alloc/src/vec/spec_from_iter_nested.rs:43
#9  0x000055555568962d in alloc::vec::spec_from_iter::{impl#0}::from_iter<usize, core::iter::adapters::map::Map<hwlocality::bitmaps::BitmapIterator<&hwlocality::bitmaps::Bitmap>, fn(hwlocality::bitmaps::indices::BitmapIndex) -> usize>> (iterator=<error reading variable: Cannot access memory at address 0x0>)
    at /rustc/8c74a5d27c644a0f7a22bb2fa8dd3ff8257bc220/library/alloc/src/vec/spec_from_iter.rs:33
#10 0x0000555555689575 in alloc::vec::{impl#14}::from_iter<usize, core::iter::adapters::map::Map<hwlocality::bitmaps::BitmapIterator<&hwlocality::bitmaps::Bitmap>, fn(hwlocality::bitmaps::indices::BitmapIndex) -> usize>> (iter=...) at /rustc/8c74a5d27c644a0f7a22bb2fa8dd3ff8257bc220/library/alloc/src/vec/mod.rs:2695
#11 0x000055555561626d in core::iter::traits::iterator::Iterator::collect<core::iter::adapters::map::Map<hwlocality::bitmaps::BitmapIterator<&hwlocality::bitmaps::Bitmap>, fn(hwlocality::bitmaps::indices::BitmapIndex) -> usize>, alloc::vec::Vec<usize, alloc::alloc::Global>> (
    self=<error reading variable: Cannot access memory at address 0x0>)
    at /rustc/8c74a5d27c644a0f7a22bb2fa8dd3ff8257bc220/library/core/src/iter/traits/iterator.rs:1895
#12 0x000055555562a9dd in benchmark::cpuload::example (tp=...) at src/cpuload.rs:88
#13 0x000055555568a7ce in benchmark::main () at src/main.rs:45
```

**Comment by uglyoldbob** [comment]
This function works.

```
pub fn example(mut tp: hwlocality::topology::Topology) {
    let root = tp.root_object();
    let cpuset = root.cpuset();
    if let Some(cpuset) = cpuset {
        for index in cpuset.iter_set().map(usize::from).collect::<Vec<_>>() {
            println!("cpu {}", index);
        }
    }
}
```

**Comment by HadrienG2** [comment]
Looks like I messed up bitmap ownership and have a fair bit of cleanup to do :( Now you know why I wanted to add more tests before publishing v1 to crates.io and advertizing it to a general audience...

**Comment by HadrienG2** [comment]
Here's a simpler reproducer:

```rust
fn wrong(topology: &Topology) {
    println!("{}", topology.cpuset());
}
```

**Comment by HadrienG2** [comment]
Should be fixed on latest master.
